from __future__ import annotations

import os


LOG_ROOT = os.environ.get("ROBOCUP_LOG_ROOT", "log")

LEARNING_RATE = 3e-4
GAMMA = 0.99
GAE_LAMBDA = 0.95
CLIP_EPSILON = 0.2
EPOCHS_PER_UPDATE = 4
BATCH_SIZE = 64
SAVE_INTERVAL = 50
TOTAL_EPISODES = 5000
CHECKPOINT_DIR = os.path.join(LOG_ROOT, "train", "checkpoints")

OBSERVATION_SIZE = 52
ACTION_SIZE = 18
HIDDEN_SIZE_1 = 256
HIDDEN_SIZE_2 = 128

VALUE_LOSS_COEF = 0.5
ENTROPY_COEF = 0.01
MAX_GRAD_NORM = 0.5

BRIDGE_HOST = "127.0.0.1"
BRIDGE_QUEUE_MAXSIZE = 512
STATE_TIMEOUT_SEC = float(os.environ.get("ROBOCUP_RL_STATE_TIMEOUT_SEC", "30.0"))
ACTION_TIMEOUT_SEC = float(os.environ.get("ROBOCUP_RL_ACTION_TIMEOUT_SEC", "5.0"))

CONTROL_UNUM = int(os.environ.get("ROBOCUP_RL_CONTROL_UNUM", "10"))
TRAIN_TEAM_NAME = os.environ.get("ROBOCUP_TRAIN_TEAM", "RLTeam")
OPPONENT_TEAM_NAME = os.environ.get("ROBOCUP_OPPONENT_TEAM", "RuleOpponent")
SERVER_HOST = os.environ.get("ROBOCUP_SERVER_HOST", "127.0.0.1")
SERVER_PORT = int(os.environ.get("ROBOCUP_SERVER_PORT", "6000"))
RCSSSERVER_BIN = os.environ.get("RCSSSERVER_BIN", "/usr/local/bin/rcssserver")
PLAYER_START_DELAY = float(os.environ.get("ROBOCUP_PLAYER_START_DELAY", "0.1"))
SERVER_CONNECT_WAIT = int(os.environ.get("ROBOCUP_SERVER_CONNECT_WAIT", "5"))
SERVER_KICK_OFF_WAIT = int(os.environ.get("ROBOCUP_SERVER_KICK_OFF_WAIT", "5"))
SERVER_GAME_OVER_WAIT = int(os.environ.get("ROBOCUP_SERVER_GAME_OVER_WAIT", "5"))
MAX_EPISODE_STEPS = int(os.environ.get("ROBOCUP_RL_MAX_EPISODE_STEPS", "6000"))
HEARTBEAT_INTERVAL = int(os.environ.get("ROBOCUP_RL_HEARTBEAT_INTERVAL", "100"))
NUM_WORKERS = int(os.environ.get("ROBOCUP_RL_NUM_WORKERS", "2"))
SERVER_PORT_STRIDE = int(os.environ.get("ROBOCUP_RL_SERVER_PORT_STRIDE", "20"))
ROLLOUT_DEVICE = os.environ.get("ROBOCUP_RL_ROLLOUT_DEVICE", "cpu")
HOME_LOG_SUBDIR = os.environ.get("ROBOCUP_RL_HOME_LOG_SUBDIR", os.path.join(LOG_ROOT, "train", "episodes"))

BRIDGE_HOST_ENV = "ROBOCUP_RL_BRIDGE_HOST"
BRIDGE_PORT_ENV = "ROBOCUP_RL_BRIDGE_PORT"
BRIDGE_AUTHKEY_ENV = "ROBOCUP_RL_BRIDGE_AUTHKEY"
EPISODE_ID_ENV = "ROBOCUP_RL_EPISODE_ID"
