Formation Static
# 4-3-3 starting layout for 11 players.
1 Goalie            -49.0    0.0
2 LeftBack          -36.0  -18.0
3 LeftCenterBack    -40.0   -6.0
4 RightCenterBack   -40.0    6.0
5 RightBack         -36.0   18.0
6 LeftMidfielder    -20.0  -12.0
7 CenterMidfielder  -22.0    0.0
8 RightMidfielder   -20.0   12.0
9 LeftForward        -6.0  -18.0
10 CenterForward     -2.0    0.0
11 RightForward      -6.0   18.0
