Formation Static
# Attacking 4-2-4 shape, high and wide
1 Goalie            -49.0    0.0
2 LeftBack          -28.0  -20.0
3 LeftCenterBack    -32.0   -6.0
4 RightCenterBack   -32.0    6.0
5 RightBack         -28.0   20.0
6 LeftMidfielder    -14.0  -10.0
7 CenterMidfielder  -18.0    0.0
8 RightMidfielder   -14.0   10.0
9 LeftForward         2.0  -20.0
10 CenterForward      5.0    0.0
11 RightForward       2.0   20.0
